-- Diagnostic comparison is species-level data cached once per species.
-- Generated by gemini-2.5-flash only when a scan's confidence_score is below the threshold.
ALTER TABLE public.species_dictionary ADD COLUMN diagnostic_primary_rationale TEXT;
ALTER TABLE public.species_dictionary ADD COLUMN diagnostic_lookalike_name TEXT;
ALTER TABLE public.species_dictionary ADD COLUMN diagnostic_differentiators_json TEXT;
