import SwiftData

typealias LocalScanRecord = MerianSchemaV10.LocalScanRecord
typealias OfflineQueuedScan = MerianSchemaV10.OfflineQueuedScan
typealias ScanCollection = MerianSchemaV10.ScanCollection
typealias PendingCloudDeletionTask = MerianSchemaV10.PendingCloudDeletionTask
