import SwiftData

typealias LocalScanRecord = MerianSchemaV7.LocalScanRecord
typealias OfflineQueuedScan = MerianSchemaV7.OfflineQueuedScan
typealias ScanCollection = MerianSchemaV7.ScanCollection
typealias PendingCloudDeletionTask = MerianSchemaV7.PendingCloudDeletionTask
