import SwiftData

typealias LocalScanRecord = MerianSchemaV8.LocalScanRecord
typealias OfflineQueuedScan = MerianSchemaV8.OfflineQueuedScan
typealias ScanCollection = MerianSchemaV8.ScanCollection
typealias PendingCloudDeletionTask = MerianSchemaV8.PendingCloudDeletionTask
