// GENERATED by services/supabase/scripts/generate_audio_comparison_plan.ts.
// Frozen source/arm/request bindings only; no runtime enablement or owner identity.

export const AUDIO_COMPARISON_PLAN_SHA256 =
  "fc30d6c938d000b2ecb994509e63b0f8e129bc5dfcb2a914a3517c8cbd4fc213";

export const AUDIO_COMPARISON_PLAN = Object.freeze(
  {
    "version": 1,
    "preparationSha256":
      "42350d978486e1a9edb409065be163b45f2d01d1182042b3e48f318e7ed43681",
    "assignments": [
      {
        "slot": 1,
        "caseId": "c0013",
        "arm": "audio-linear-full-windows-v1",
        "sourceWavSha256":
          "214e0f3f8e9c35f966503033ae159edb524498e0532700daa3802359ff7f8303",
        "sourceByteLength": 506924,
        "processedWavSha256":
          "039adae1fdd8cfbaa7daa7a39df643f06459dd536b4e8145dc93898e57a988c1",
        "providerRequestSha256":
          "e86fa568e8e403bfb24096ba890c1985a24ca55334fd3dcdd620544c0cb129c2",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 2,
        "caseId": "c0013",
        "arm": "audio-sinc-partial-tail-v1",
        "sourceWavSha256":
          "214e0f3f8e9c35f966503033ae159edb524498e0532700daa3802359ff7f8303",
        "sourceByteLength": 506924,
        "processedWavSha256":
          "3a68bd5965993de8ac0c4c282da98d1bddcc5c11998abd2408d5dac379d5dce2",
        "providerRequestSha256":
          "8a1ff98f77c5fbe042348e5b410712a8ed87b4343e5e21ce9acf903ced3c4d22",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 3,
        "caseId": "c0014",
        "arm": "audio-sinc-partial-tail-v1",
        "sourceWavSha256":
          "4696164a9407ecf5242425fd4f803ad3c62e4d9d765c28e1dc7b1cbf330abab8",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "6560d967771137d8b3598e0a145782a68e4e5f4ca6e6e5059eb91dbeb22ead32",
        "providerRequestSha256":
          "1ee3cded1f4aacee074688c7f01d88d345308366113125f63041ba67cf94cd14",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 4,
        "caseId": "c0014",
        "arm": "audio-linear-full-windows-v1",
        "sourceWavSha256":
          "4696164a9407ecf5242425fd4f803ad3c62e4d9d765c28e1dc7b1cbf330abab8",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "b691d815635fed7e48f08adeaa2d9634f8a17852db7a8330d201a98ce6423c60",
        "providerRequestSha256":
          "230f5dfdc81615cbbc922a30dfdae9272956c7291565b15ed8e36fba9a12b521",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 5,
        "caseId": "c0015",
        "arm": "audio-linear-full-windows-v1",
        "sourceWavSha256":
          "5d327fae2cea263c348572557ab1a2774ab0d7a8c0a612970ade1b550640154c",
        "sourceByteLength": 880172,
        "processedWavSha256":
          "bf5f801240adbcf67fbea62c9b3356e4f5d28ab06120c173d4895f5c91f57533",
        "providerRequestSha256":
          "84deb3cb918c9c830c8b642d22fe3c5186186c8848dd55d016cdb6f6e059739e",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 6,
        "caseId": "c0015",
        "arm": "audio-sinc-partial-tail-v1",
        "sourceWavSha256":
          "5d327fae2cea263c348572557ab1a2774ab0d7a8c0a612970ade1b550640154c",
        "sourceByteLength": 880172,
        "processedWavSha256":
          "5ee6d5e1732c89e7eeb20b1edf152d627993004cebdb9aefc773dd9f8b8496cd",
        "providerRequestSha256":
          "19354d37b472470aece13948a44bc9134d9095caacffc35b8e624070ec3d5828",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 7,
        "caseId": "c0016",
        "arm": "audio-sinc-partial-tail-v1",
        "sourceWavSha256":
          "f67b22b951b922cd222441e39acbfe67a7f6253d8c7e2c07631308726d274b0f",
        "sourceByteLength": 447020,
        "processedWavSha256":
          "29898907d1e59e696deb9e1bd7322268df10291883bacf037320b38b097bde4e",
        "providerRequestSha256":
          "144d768d92409043e3b9de77b370ee18b35b4c5ae8feee1e882b9b36a2ed728b",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 8,
        "caseId": "c0016",
        "arm": "audio-linear-full-windows-v1",
        "sourceWavSha256":
          "f67b22b951b922cd222441e39acbfe67a7f6253d8c7e2c07631308726d274b0f",
        "sourceByteLength": 447020,
        "processedWavSha256":
          "28563d3c4b6e0628a5bd3b03e334fbfb2e4ea83b338f0c78051da088a4347381",
        "providerRequestSha256":
          "648a46fd1aa17b2642a9487e903c1a7c45ddfa9761559d859e7030c256322d88",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 9,
        "caseId": "c0017",
        "arm": "audio-linear-full-windows-v1",
        "sourceWavSha256":
          "dfabd74210a85b46a80a42656c79586c144145108a692e32d03a17a836a4ac8a",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "dcfb5d38e22384a49f7b89a7620660df3a90830ec3f8e45fa5de9ad88bc1781f",
        "providerRequestSha256":
          "3a86d484d6f37f4bddcc338ca3d367627bd317eed7a59afb83701adb5beda1aa",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 10,
        "caseId": "c0017",
        "arm": "audio-sinc-partial-tail-v1",
        "sourceWavSha256":
          "dfabd74210a85b46a80a42656c79586c144145108a692e32d03a17a836a4ac8a",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "41d4ed55f3cede3cfed9ab4683fbd3d91b116fd7e774c3a0eff8c02bae414e97",
        "providerRequestSha256":
          "43ad87da85a6098b0c888e31831ae3d59ff9ae5a359f4789a6d8aeaf22b0c58c",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 11,
        "caseId": "c0018",
        "arm": "audio-sinc-partial-tail-v1",
        "sourceWavSha256":
          "1803ceef8ae9ad9e71e7fcfa322208a8970485ffdf84a466770e73fb15b1c711",
        "sourceByteLength": 880172,
        "processedWavSha256":
          "57274ab66c13e03464f3d0407eeaadc64401012ff7b22afcf48da8e70c560aeb",
        "providerRequestSha256":
          "40f829199d2d97ee33ae9ac2cd945ad27c84fed82108b916a4a219750d2ccdaa",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 12,
        "caseId": "c0018",
        "arm": "audio-linear-full-windows-v1",
        "sourceWavSha256":
          "1803ceef8ae9ad9e71e7fcfa322208a8970485ffdf84a466770e73fb15b1c711",
        "sourceByteLength": 880172,
        "processedWavSha256":
          "e377172d4eb59e80b41a55c4ce2cd67a5848ffd2b7caf712be855a0698fe4e40",
        "providerRequestSha256":
          "08872a4dbeace4b0dd446bd185992f8e288180dac1d254e145958d13931f8801",
        "policySha256":
          "e87be3d9d907ae1ab710861181f19ed2bc542fb207c075c3b316797f734ce99c",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
    ],
  } as const,
);
