// GENERATED by services/supabase/scripts/generate_audio_prompt_comparison_plan.ts.
// Frozen prompt experiment only; no enablement or owner identity.

export const AUDIO_PROMPT_COMPARISON_PLAN_SHA256 =
  "8019602955455d8c8fb83ff368a1e54a6dfee58e1f4680f801e45bcee30d8dee";

export const AUDIO_PROMPT_COMPARISON_PLAN = Object.freeze(
  {
    "version": 1,
    "preparationSha256":
      "068f74f51f4e7c81a2eaae36f1f51363e84fa57e5f4dadf6694e007fe1fb63bb",
    "designSha256":
      "54bb0b5469230b57c507e63ea55d61e3e201cacbd4115dcc0e418ed1aa81df32",
    "startsNotBefore": "2026-09-24T16:49:06.497Z",
    "expiresNotAfter": "2026-10-24T00:00:00.000Z",
    "assignments": [
      {
        "slot": 1,
        "block": 1,
        "repeat": 1,
        "caseId": "c0025",
        "arm": "A",
        "sourceWavSha256":
          "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
        "providerRequestSha256":
          "94899b80e308bb14ef1e096dfb23b55d77252bd913d6abb3bf6f65b4fe133add",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 2,
        "block": 1,
        "repeat": 1,
        "caseId": "c0025",
        "arm": "B",
        "sourceWavSha256":
          "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
        "providerRequestSha256":
          "0db615a433e790bec42ae0b7d90b2a59c4c122c3045bd8ba4b130f997fea8051",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 3,
        "block": 1,
        "repeat": 1,
        "caseId": "c0020",
        "arm": "B",
        "sourceWavSha256":
          "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
        "sourceByteLength": 285740,
        "processedWavSha256":
          "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
        "providerRequestSha256":
          "113fcd3b483e50ac40145ed4a3e967e80ad1d1577883041511e1e8cc80afbed4",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 4,
        "block": 1,
        "repeat": 1,
        "caseId": "c0020",
        "arm": "A",
        "sourceWavSha256":
          "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
        "sourceByteLength": 285740,
        "processedWavSha256":
          "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
        "providerRequestSha256":
          "abf7806787686c8d993739d7944a462638b9ef1b2bf0e21e548c52ea85ba1981",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 5,
        "block": 1,
        "repeat": 1,
        "caseId": "c0023",
        "arm": "A",
        "sourceWavSha256":
          "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
        "sourceByteLength": 437804,
        "processedWavSha256":
          "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
        "providerRequestSha256":
          "d4ec0894f5b693bc3428a3fe4f04232514088bbfd6e35e1f889d96cff5c71783",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 6,
        "block": 1,
        "repeat": 1,
        "caseId": "c0023",
        "arm": "B",
        "sourceWavSha256":
          "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
        "sourceByteLength": 437804,
        "processedWavSha256":
          "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
        "providerRequestSha256":
          "53645173f1f8cee4927508b34392e5f79abdc9a759d263370df0bdce098cc191",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 7,
        "block": 1,
        "repeat": 1,
        "caseId": "c0026",
        "arm": "B",
        "sourceWavSha256":
          "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
        "sourceByteLength": 478440,
        "processedWavSha256":
          "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
        "providerRequestSha256":
          "e54017a1d6d1805f9b824e9b58c1753aa6bc8d41f0f5c4d7d1a58f2b0dff10b3",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 8,
        "block": 1,
        "repeat": 1,
        "caseId": "c0026",
        "arm": "A",
        "sourceWavSha256":
          "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
        "sourceByteLength": 478440,
        "processedWavSha256":
          "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
        "providerRequestSha256":
          "7f7e493c1129d36646006d2d42ea30d5a5124c699f0ff5d8f95bfea96f27aa07",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 9,
        "block": 1,
        "repeat": 1,
        "caseId": "c0021",
        "arm": "A",
        "sourceWavSha256":
          "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
        "sourceByteLength": 875564,
        "processedWavSha256":
          "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
        "providerRequestSha256":
          "ba7ce5caea5ce5ae8badb2655d2ad1f092b0f62ff2ddcdab16ea47a63f6fbb19",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 10,
        "block": 1,
        "repeat": 1,
        "caseId": "c0021",
        "arm": "B",
        "sourceWavSha256":
          "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
        "sourceByteLength": 875564,
        "processedWavSha256":
          "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
        "providerRequestSha256":
          "a148c514aacff358eeda4d665ac5b2b61d21580da06aae68b64c723b96cac83a",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 11,
        "block": 1,
        "repeat": 1,
        "caseId": "c0024",
        "arm": "B",
        "sourceWavSha256":
          "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
        "sourceByteLength": 476972,
        "processedWavSha256":
          "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
        "providerRequestSha256":
          "566428c0cf6498ceef36749fb79b973a5a9958d261072245f8590f4f51c3a89a",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 12,
        "block": 1,
        "repeat": 1,
        "caseId": "c0024",
        "arm": "A",
        "sourceWavSha256":
          "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
        "sourceByteLength": 476972,
        "processedWavSha256":
          "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
        "providerRequestSha256":
          "c4fb287be8f29fd3217918524f45297609b19294132d064f7f0c3604041d8e6e",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 13,
        "block": 2,
        "repeat": 2,
        "caseId": "c0023",
        "arm": "B",
        "sourceWavSha256":
          "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
        "sourceByteLength": 437804,
        "processedWavSha256":
          "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
        "providerRequestSha256":
          "53645173f1f8cee4927508b34392e5f79abdc9a759d263370df0bdce098cc191",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 14,
        "block": 2,
        "repeat": 2,
        "caseId": "c0023",
        "arm": "A",
        "sourceWavSha256":
          "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
        "sourceByteLength": 437804,
        "processedWavSha256":
          "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
        "providerRequestSha256":
          "d4ec0894f5b693bc3428a3fe4f04232514088bbfd6e35e1f889d96cff5c71783",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 15,
        "block": 2,
        "repeat": 2,
        "caseId": "c0026",
        "arm": "A",
        "sourceWavSha256":
          "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
        "sourceByteLength": 478440,
        "processedWavSha256":
          "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
        "providerRequestSha256":
          "7f7e493c1129d36646006d2d42ea30d5a5124c699f0ff5d8f95bfea96f27aa07",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 16,
        "block": 2,
        "repeat": 2,
        "caseId": "c0026",
        "arm": "B",
        "sourceWavSha256":
          "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
        "sourceByteLength": 478440,
        "processedWavSha256":
          "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
        "providerRequestSha256":
          "e54017a1d6d1805f9b824e9b58c1753aa6bc8d41f0f5c4d7d1a58f2b0dff10b3",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 17,
        "block": 2,
        "repeat": 2,
        "caseId": "c0021",
        "arm": "B",
        "sourceWavSha256":
          "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
        "sourceByteLength": 875564,
        "processedWavSha256":
          "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
        "providerRequestSha256":
          "a148c514aacff358eeda4d665ac5b2b61d21580da06aae68b64c723b96cac83a",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 18,
        "block": 2,
        "repeat": 2,
        "caseId": "c0021",
        "arm": "A",
        "sourceWavSha256":
          "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
        "sourceByteLength": 875564,
        "processedWavSha256":
          "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
        "providerRequestSha256":
          "ba7ce5caea5ce5ae8badb2655d2ad1f092b0f62ff2ddcdab16ea47a63f6fbb19",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 19,
        "block": 2,
        "repeat": 2,
        "caseId": "c0024",
        "arm": "A",
        "sourceWavSha256":
          "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
        "sourceByteLength": 476972,
        "processedWavSha256":
          "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
        "providerRequestSha256":
          "c4fb287be8f29fd3217918524f45297609b19294132d064f7f0c3604041d8e6e",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 20,
        "block": 2,
        "repeat": 2,
        "caseId": "c0024",
        "arm": "B",
        "sourceWavSha256":
          "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
        "sourceByteLength": 476972,
        "processedWavSha256":
          "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
        "providerRequestSha256":
          "566428c0cf6498ceef36749fb79b973a5a9958d261072245f8590f4f51c3a89a",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 21,
        "block": 2,
        "repeat": 2,
        "caseId": "c0025",
        "arm": "B",
        "sourceWavSha256":
          "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
        "providerRequestSha256":
          "0db615a433e790bec42ae0b7d90b2a59c4c122c3045bd8ba4b130f997fea8051",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 22,
        "block": 2,
        "repeat": 2,
        "caseId": "c0025",
        "arm": "A",
        "sourceWavSha256":
          "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
        "providerRequestSha256":
          "94899b80e308bb14ef1e096dfb23b55d77252bd913d6abb3bf6f65b4fe133add",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 23,
        "block": 2,
        "repeat": 2,
        "caseId": "c0020",
        "arm": "A",
        "sourceWavSha256":
          "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
        "sourceByteLength": 285740,
        "processedWavSha256":
          "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
        "providerRequestSha256":
          "abf7806787686c8d993739d7944a462638b9ef1b2bf0e21e548c52ea85ba1981",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 24,
        "block": 2,
        "repeat": 2,
        "caseId": "c0020",
        "arm": "B",
        "sourceWavSha256":
          "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
        "sourceByteLength": 285740,
        "processedWavSha256":
          "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
        "providerRequestSha256":
          "113fcd3b483e50ac40145ed4a3e967e80ad1d1577883041511e1e8cc80afbed4",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 25,
        "block": 3,
        "repeat": 3,
        "caseId": "c0021",
        "arm": "A",
        "sourceWavSha256":
          "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
        "sourceByteLength": 875564,
        "processedWavSha256":
          "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
        "providerRequestSha256":
          "ba7ce5caea5ce5ae8badb2655d2ad1f092b0f62ff2ddcdab16ea47a63f6fbb19",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 26,
        "block": 3,
        "repeat": 3,
        "caseId": "c0021",
        "arm": "B",
        "sourceWavSha256":
          "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
        "sourceByteLength": 875564,
        "processedWavSha256":
          "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
        "providerRequestSha256":
          "a148c514aacff358eeda4d665ac5b2b61d21580da06aae68b64c723b96cac83a",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 27,
        "block": 3,
        "repeat": 3,
        "caseId": "c0024",
        "arm": "B",
        "sourceWavSha256":
          "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
        "sourceByteLength": 476972,
        "processedWavSha256":
          "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
        "providerRequestSha256":
          "566428c0cf6498ceef36749fb79b973a5a9958d261072245f8590f4f51c3a89a",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 28,
        "block": 3,
        "repeat": 3,
        "caseId": "c0024",
        "arm": "A",
        "sourceWavSha256":
          "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
        "sourceByteLength": 476972,
        "processedWavSha256":
          "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
        "providerRequestSha256":
          "c4fb287be8f29fd3217918524f45297609b19294132d064f7f0c3604041d8e6e",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 29,
        "block": 3,
        "repeat": 3,
        "caseId": "c0025",
        "arm": "A",
        "sourceWavSha256":
          "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
        "providerRequestSha256":
          "94899b80e308bb14ef1e096dfb23b55d77252bd913d6abb3bf6f65b4fe133add",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 30,
        "block": 3,
        "repeat": 3,
        "caseId": "c0025",
        "arm": "B",
        "sourceWavSha256":
          "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
        "sourceByteLength": 882044,
        "processedWavSha256":
          "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
        "providerRequestSha256":
          "0db615a433e790bec42ae0b7d90b2a59c4c122c3045bd8ba4b130f997fea8051",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 31,
        "block": 3,
        "repeat": 3,
        "caseId": "c0020",
        "arm": "B",
        "sourceWavSha256":
          "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
        "sourceByteLength": 285740,
        "processedWavSha256":
          "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
        "providerRequestSha256":
          "113fcd3b483e50ac40145ed4a3e967e80ad1d1577883041511e1e8cc80afbed4",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 32,
        "block": 3,
        "repeat": 3,
        "caseId": "c0020",
        "arm": "A",
        "sourceWavSha256":
          "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
        "sourceByteLength": 285740,
        "processedWavSha256":
          "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
        "providerRequestSha256":
          "abf7806787686c8d993739d7944a462638b9ef1b2bf0e21e548c52ea85ba1981",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 33,
        "block": 3,
        "repeat": 3,
        "caseId": "c0023",
        "arm": "A",
        "sourceWavSha256":
          "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
        "sourceByteLength": 437804,
        "processedWavSha256":
          "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
        "providerRequestSha256":
          "d4ec0894f5b693bc3428a3fe4f04232514088bbfd6e35e1f889d96cff5c71783",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 34,
        "block": 3,
        "repeat": 3,
        "caseId": "c0023",
        "arm": "B",
        "sourceWavSha256":
          "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
        "sourceByteLength": 437804,
        "processedWavSha256":
          "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
        "providerRequestSha256":
          "53645173f1f8cee4927508b34392e5f79abdc9a759d263370df0bdce098cc191",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 35,
        "block": 3,
        "repeat": 3,
        "caseId": "c0026",
        "arm": "B",
        "sourceWavSha256":
          "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
        "sourceByteLength": 478440,
        "processedWavSha256":
          "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
        "providerRequestSha256":
          "e54017a1d6d1805f9b824e9b58c1753aa6bc8d41f0f5c4d7d1a58f2b0dff10b3",
        "policySha256":
          "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
      {
        "slot": 36,
        "block": 3,
        "repeat": 3,
        "caseId": "c0026",
        "arm": "A",
        "sourceWavSha256":
          "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
        "sourceByteLength": 478440,
        "processedWavSha256":
          "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
        "providerRequestSha256":
          "7f7e493c1129d36646006d2d42ea30d5a5124c699f0ff5d8f95bfea96f27aa07",
        "policySha256":
          "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
        "confidenceSha256":
          "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
      },
    ],
  } as const,
);
