// GENERATED by services/supabase/scripts/generate_field_chat_deployment_identity.ts.
// Do not edit by hand. The generator excludes this file from its own digest.

export const FIELD_CHAT_BUNDLE_SHA256 = Object.freeze(
  {
    "explore-post-chat":
      "8ec8202be9c2c19d5b6ead3fd9bf034990e40c2f5a76b8c9651cc0f0c7b03049",
    "insight-chat":
      "f880bc0491535a3be1e204812e16f3a3bf438fdabda7961a4f403f00b481c984",
    "species-dictionary-chat":
      "153bf7862eadfb747acfa879d1edb7004030210afbf81d43f9fa013e8d37c640",
  } as const,
);

export type FieldChatDeploymentFunction = keyof typeof FIELD_CHAT_BUNDLE_SHA256;
