// GENERATED by services/supabase/scripts/generate_field_chat_deployment_identity.ts.
// Do not edit by hand. The generator excludes this file from its own digest.

export const FIELD_CHAT_BUNDLE_SHA256 = Object.freeze(
  {
    "explore-post-chat":
      "4860f278d848053ccf6d9aa8a84cdee71419eca77738826e36d630c36ba9a5f4",
    "insight-chat":
      "30e015ded040d75227b5aef39f41740e7199e25dedfd31c0b735f45741a1e94b",
    "species-dictionary-chat":
      "dabda27c8649b793024e53fc9d3ab1f67c1b5721fff251e7f0a0255d6adf2cac",
  } as const,
);

export type FieldChatDeploymentFunction = keyof typeof FIELD_CHAT_BUNDLE_SHA256;
