// GENERATED by services/supabase/scripts/generate_field_chat_deployment_identity.ts.
// Do not edit by hand. The generator excludes this file from its own digest.

export const FIELD_CHAT_BUNDLE_SHA256 = Object.freeze(
  {
    "explore-post-chat":
      "e7d9b7cb0a7953a8e12833156f9f5d21021c1463e1a86e7e42f02f4b758d611b",
    "insight-chat":
      "9546b509404608533e68597f86435bf55730755d2a78765d23a4ff088662b08d",
    "species-dictionary-chat":
      "68d17bc187b4e9f7bd4a61d6a803ec46fd88ee19665bab9d438a32ea1d99f8d4",
  } as const,
);

export type FieldChatDeploymentFunction = keyof typeof FIELD_CHAT_BUNDLE_SHA256;
