export const EXPORT_PAGE_SIZE = 100;
export const MAXIMUM_EXPORT_SOURCE_PAGE_BYTES = 256 * 1024;
export const MAXIMUM_WORK_CHUNK_BYTES = 512 * 1024;

export const MAXIMUM_DWCA_IMAGE_URLS = 24;
export const MAXIMUM_DWCA_IMAGE_URL_BYTES = 4_096;
export const MAXIMUM_DWCA_INTERACTIONS = 10;
export const MAXIMUM_DWCA_INTERACTION_BYTES = 2_048;
export const MAXIMUM_DWCA_SCIENTIFIC_NAME_BYTES = 1_024;
export const MAXIMUM_DWCA_TAXON_RANK_BYTES = 512;
export const MAXIMUM_DWCA_IUCN_STATUS_BYTES = 128;
