import Foundation
import SwiftData

// Added in V37:
//   LocalScanRecord.observationContextJSON — String?
//     Raw JSON of the ObservationContext staged by the user. NULL for image-only scans.
//   OfflineQueuedScan.observationContextJSON — String?
//     JSON-encoded ObservationContext preserved for offline-retry reconstruction.
//   OfflineQueuedScan.audioFilePath — String?
//     Reserved placeholder for a companion audio recording clip (future AudioRecordingView).
// Unchanged entities alias the preceding frozen snapshots so later active-model
// changes cannot alter this released schema's checksum.
enum MerianSchemaV37: VersionedSchema {
    static var versionIdentifier = Schema.Version(37, 0, 0)

    static var models: [any PersistentModel.Type] {
        [MerianSchemaV37.LocalScanRecord.self, OfflineQueuedScan.self,
         MerianSchemaV37.ScanCollection.self, PendingCloudDeletionTask.self,
         MerianSchemaV37.UserSpeciesPreference.self]
    }

    typealias UserSpeciesPreference = MerianSchemaV36.UserSpeciesPreference
}

// MARK: - Frozen LocalScanRecord snapshot for MerianSchemaV37
// Generated by: python3 .agents/workflows/freeze_schema.py 37
// Captures the LocalScanRecord shape AT V37 — before any new fields were added.
// DO NOT modify after committing. Checksums must remain stable forever.
extension MerianSchemaV37 {
    @Model
    final class LocalScanRecord {
        @Attribute(.unique) var id: String
        var speciesId: String
        var scientificName: String
        var commonName: String
        var timestamp: Date
        var captureDate: Date?
        var localImagePath: String?

        var semanticTags: [String]
        /// Hazard classification returned by the AI. One of: "none" | "poisonous" | "venomous" | "allergenic" | "irritant".
        var hazardType: String = "none"
        var isBiological: Bool
        var isLiveCapture: Bool
        var isInvasive: Bool
        var ecologyType: String
        var wikipediaUrl: String?
        /// Wikipedia summary paragraph for this species. Cached from the Wikipedia REST API.
        @Attribute(originalName: "wikipediaExtract") var wikipediaOverview: String?
        var referenceImageUrl: String?
        var additionalImagePaths: [String]?
        var confidenceScore: Double?
        @Attribute var isLocallyArchived: Bool = false

        var taxonomyKingdom: String?
        var taxonomyPhylum: String?
        var taxonomyClass: String?
        var taxonomyOrder: String?
        var taxonomyFamily: String?
        var taxonomyGenus: String?

        var locationName: String?
        var weatherCondition: String?
        var weatherTemperatureF: Double?

        var collections: [MerianSchemaV37.ScanCollection]? = []

        var similarSpecies: [String]?
        var lookalikesData: Data?
        /// JSON-encoded `[IdentificationCandidate]` — the model's top alternative species when
        /// `confidenceScore` fell below the tier-specific `MerianConfig.diagnosticTrigger` threshold.
        /// Nil for high-confidence scans and all scans captured before V28.
        @Attribute var candidatesData: Data?

        /// Scientific name chosen by the user when they disagreed with the AI's identification.
        /// Nil means no override — AI identification accepted by default. Cloud-synced.
        @Attribute var userIdentificationOverride: String?
        /// Local-only flag set when user taps "Yes, correct" on the CandidatesCard prompt.
        /// Suppresses the "Was the AI correct?" prompt on re-open. Not synced to cloud.
        @Attribute var userConfirmedIdentification: Bool = false

        /// Legacy local moderation flag retained for schema compatibility.
        /// No longer drives Insight confidence or candidate-review UI.
        @Attribute var isFlagged: Bool = false

        @Attribute var iucnRedListStatus: String?
        @Attribute var gpsLatitude: Double?
        @Attribute var gpsLongitude: Double?
        @Attribute var gpsElevation: Double?
        @Attribute var zoomFactor: Double?

        /// Per-scan AI vision reasoning — unique to the specific photo submitted.
        @Attribute var aiReasoning: String?
        @Attribute var habitatDescription: String?
        /// GBIF species usage key for occurrence density heatmap tiles.
        @Attribute var gbifTaxonKey: Int?

        @Attribute var estimatedSizeCm: Double?
        @Attribute var lifeStage: String?
        @Attribute var reproductiveCondition: String?
        @Attribute var individualCount: Int?
        @Attribute var ecologicalInteractions: [String]?
        @Attribute var inferenceTier: String?

        /// User-defined custom tags for personal categorization and search indexing.
        @Attribute var customTags: [String] = []

        /// Tracks if a user has opened the scan's insight sheet. Defaults to true so historic scans don't receive "New" badges.
        var hasBeenViewed: Bool = true

        /// Gemini's photographic quality score (0–100) for the submitted image.
        /// Derived from `image_quality.overall_score` in the edge response.
        /// Nil for scans captured before V30.
        @Attribute var imageQualityScore: Int?

        /// All known English vernacular synonyms beyond `commonName`.
        /// Sourced from GBIF vernacular names during background enrichment.
        /// Nil for scans captured before V34 or species not yet enriched.
        @Attribute var alternativeCommonNames: [String]?

        @Attribute var confirmedSpeciesId: String?

        // Changed to optional so SQLite lightweight migration can add the column correctly
        @Attribute var userReviewStateRaw: String? = "unreviewed"

        /// Raw JSON string of the structured `ObservationContext` staged by the user before submission.
        /// Set once at scan creation; never mutated after.
        /// `nil` for image-only scans or scans captured before V37.
        @Attribute var observationContextJSON: String?

        /// Local file path to the audio recording associated with this scan.
        /// Added in SchemaV38.

        var userReviewState: UserReviewState {
            get { UserReviewState(rawValue: userReviewStateRaw ?? UserReviewState.unreviewed.rawValue) ?? .unreviewed }
            set { userReviewStateRaw = newValue.rawValue }
        }

        init(
            id: String = UUID().uuidString,
            speciesId: String,
            scientificName: String,
            commonName: String,
            timestamp: Date = Date(),
            captureDate: Date? = nil,
            localImagePath: String? = nil,
            semanticTags: [String] = [],
            hazardType: String = "none",
            isBiological: Bool = true,
            isLiveCapture: Bool = true,
            isInvasive: Bool = false,
            ecologyType: String = "unknown",
            wikipediaUrl: String? = nil,
            wikipediaOverview: String? = nil,
            referenceImageUrl: String? = nil,
            additionalImagePaths: [String]? = nil,
            confidenceScore: Double? = nil,
            isLocallyArchived: Bool = false,
            taxonomyKingdom: String? = nil,
            taxonomyPhylum: String? = nil,
            taxonomyClass: String? = nil,
            taxonomyOrder: String? = nil,
            taxonomyFamily: String? = nil,
            taxonomyGenus: String? = nil,
            locationName: String? = nil,
            weatherCondition: String? = nil,
            weatherTemperatureF: Double? = nil,
            collections: [MerianSchemaV37.ScanCollection]? = [],
            similarSpecies: [String]? = nil,
            lookalikesData: Data? = nil,
            candidatesData: Data? = nil,
            iucnRedListStatus: String? = nil,
            gpsLatitude: Double? = nil,
            gpsLongitude: Double? = nil,
            gpsElevation: Double? = nil,
            zoomFactor: Double? = nil,
            aiReasoning: String? = nil,
            habitatDescription: String? = nil,
            gbifTaxonKey: Int? = nil,
            estimatedSizeCm: Double? = nil,
            lifeStage: String? = nil,
            reproductiveCondition: String? = nil,
            individualCount: Int? = nil,
            ecologicalInteractions: [String]? = nil,
            inferenceTier: String? = nil,
            customTags: [String] = [],
            hasBeenViewed: Bool = false,
            userIdentificationOverride: String? = nil,
            userConfirmedIdentification: Bool = false,
            isFlagged: Bool = false,
            imageQualityScore: Int? = nil,
            alternativeCommonNames: [String]? = nil,
            confirmedSpeciesId: String? = nil,
            userReviewStateRaw: String? = nil,
            observationContextJSON: String? = nil,
        ) {

            self.id = id
            self.speciesId = speciesId
            self.scientificName = scientificName
            self.commonName = commonName
            self.timestamp = timestamp
            self.captureDate = captureDate
            self.localImagePath = localImagePath
            self.semanticTags = semanticTags
            self.hazardType = hazardType
            self.isBiological = isBiological
            self.isLiveCapture = isLiveCapture
            self.isInvasive = isInvasive
            self.ecologyType = ecologyType
            self.wikipediaUrl = wikipediaUrl
            self.wikipediaOverview = wikipediaOverview
            self.referenceImageUrl = referenceImageUrl
            self.additionalImagePaths = additionalImagePaths
            self.confidenceScore = confidenceScore
            self.isLocallyArchived = isLocallyArchived

            self.taxonomyKingdom = taxonomyKingdom
            self.taxonomyPhylum = taxonomyPhylum
            self.taxonomyClass = taxonomyClass
            self.taxonomyOrder = taxonomyOrder
            self.taxonomyFamily = taxonomyFamily
            self.taxonomyGenus = taxonomyGenus

            self.locationName = locationName
            self.weatherCondition = weatherCondition
            self.weatherTemperatureF = weatherTemperatureF

            self.collections = collections

            self.similarSpecies = similarSpecies
            self.lookalikesData = lookalikesData
            self.candidatesData = candidatesData
            self.iucnRedListStatus = iucnRedListStatus
            self.gpsLatitude = gpsLatitude
            self.gpsLongitude = gpsLongitude
            self.gpsElevation = gpsElevation
            self.zoomFactor = zoomFactor

            self.aiReasoning = aiReasoning
            self.habitatDescription = habitatDescription
            self.gbifTaxonKey = gbifTaxonKey

            self.estimatedSizeCm = estimatedSizeCm
            self.lifeStage = lifeStage
            self.reproductiveCondition = reproductiveCondition
            self.individualCount = individualCount
            self.ecologicalInteractions = ecologicalInteractions
            self.inferenceTier = inferenceTier
            self.customTags = customTags
            self.hasBeenViewed = hasBeenViewed
            self.userIdentificationOverride = userIdentificationOverride
            self.userConfirmedIdentification = userConfirmedIdentification
            self.isFlagged = isFlagged
            self.imageQualityScore = imageQualityScore
            self.alternativeCommonNames = alternativeCommonNames
            self.confirmedSpeciesId = confirmedSpeciesId
            self.userReviewStateRaw = userReviewStateRaw
            self.observationContextJSON = observationContextJSON
        }
    }

    @Model
    final class ScanCollection {
        @Attribute(.unique) var id: String = UUID().uuidString
        var name: String
        var createdAt: Date = Date()
        var isDeleted: Bool = false

        @Relationship(inverse: \MerianSchemaV37.LocalScanRecord.collections) var scans: [MerianSchemaV37.LocalScanRecord]? = []

        init(id: String = UUID().uuidString, name: String, createdAt: Date = Date(), isDeleted: Bool = false, scans: [MerianSchemaV37.LocalScanRecord]? = []) {
            self.id = id
            self.name = name
            self.createdAt = createdAt
            self.isDeleted = isDeleted
            self.scans = scans
        }
    }
}
