default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure dependencies and Xcode project format are completely synced
    sh("cd .. && xcodegen generate")
    
    # Increment the build number automatically based on App Store Connect
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    
    # Build and archive the workspace
    build_app(
      scheme: "Merian",
      export_method: "app-store"
    )
    
    # Upload to TestFlight
    upload_to_testflight
  end
end
