import { join } from "node:path";
import {
  buildAllFunctionGraphs,
  functionsRoot,
  repoRelative,
} from "./function_dependency_tools.ts";

export const FIELD_CHAT_FUNCTION_NAMES = Object.freeze(
  [
    "explore-post-chat",
    "insight-chat",
    "species-dictionary-chat",
  ] as const,
);

export type FieldChatFunctionName = (typeof FIELD_CHAT_FUNCTION_NAMES)[number];

const GENERATED_IDENTITY_PATH = join(
  functionsRoot,
  "_shared",
  "fieldChatDeploymentIdentity.ts",
);
const SHARED_DEPLOYMENT_INPUTS = Object.freeze([
  join(functionsRoot, "deno.json"),
  join(functionsRoot, "dependencies.lock"),
]);
const HEX_DIGEST_PATTERN = /^[0-9a-f]{64}$/;

async function sha256Bytes(bytes: Uint8Array): Promise<string> {
  const ownedBytes = new Uint8Array(bytes.byteLength);
  ownedBytes.set(bytes);
  const digest = await crypto.subtle.digest("SHA-256", ownedBytes);
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

async function existingFunctionConfig(
  functionName: FieldChatFunctionName,
): Promise<string[]> {
  const path = join(functionsRoot, functionName, "deno.json");
  try {
    return (await Deno.stat(path)).isFile ? [path] : [];
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return [];
    throw error;
  }
}

async function digestFiles(paths: readonly string[]): Promise<string> {
  const canonicalEntries: string[] = [];
  for (const path of [...new Set(paths)].sort()) {
    const fileDigest = await sha256Bytes(await Deno.readFile(path));
    canonicalEntries.push(`${repoRelative(path)}\0${fileDigest}\n`);
  }
  return await sha256Bytes(
    new TextEncoder().encode(canonicalEntries.join("")),
  );
}

export async function computeFieldChatBundleDigests(): Promise<
  Readonly<Record<FieldChatFunctionName, string>>
> {
  const graphs = await buildAllFunctionGraphs();
  const result = {} as Record<FieldChatFunctionName, string>;
  for (const functionName of FIELD_CHAT_FUNCTION_NAMES) {
    const graph = graphs.find((candidate) => candidate.name === functionName);
    if (!graph) {
      throw new Error(`Field Chat function graph is missing ${functionName}`);
    }
    const runtimeFiles = [...graph.files].filter((path) =>
      path !== GENERATED_IDENTITY_PATH
    );
    result[functionName] = await digestFiles([
      ...runtimeFiles,
      ...SHARED_DEPLOYMENT_INPUTS,
      ...await existingFunctionConfig(functionName),
    ]);
  }
  return Object.freeze(result);
}

export function renderFieldChatDeploymentIdentity(
  digests: Readonly<Record<FieldChatFunctionName, string>>,
): string {
  for (const functionName of FIELD_CHAT_FUNCTION_NAMES) {
    if (!HEX_DIGEST_PATTERN.test(digests[functionName])) {
      throw new Error(`Bundle digest is malformed for ${functionName}`);
    }
  }
  const entries = FIELD_CHAT_FUNCTION_NAMES.map((functionName) =>
    `    "${functionName}":\n      "${digests[functionName]}",`
  ).join("\n");
  return `// GENERATED by services/supabase/scripts/generate_field_chat_deployment_identity.ts.\n// Do not edit by hand. The generator excludes this file from its own digest.\n\nexport const FIELD_CHAT_BUNDLE_SHA256 = Object.freeze(\n  {\n${entries}\n  } as const,\n);\n\nexport type FieldChatDeploymentFunction = keyof typeof FIELD_CHAT_BUNDLE_SHA256;\n`;
}

function argumentValue(name: string): string | undefined {
  const index = Deno.args.indexOf(name);
  return index >= 0 ? Deno.args[index + 1] : undefined;
}

if (import.meta.main) {
  const digests = await computeFieldChatBundleDigests();
  const printFunction = argumentValue("--print");
  if (printFunction !== undefined) {
    if (
      !(FIELD_CHAT_FUNCTION_NAMES as readonly string[]).includes(
        printFunction,
      )
    ) {
      throw new Error(`Unknown Field Chat function: ${printFunction}`);
    }
    console.log(digests[printFunction as FieldChatFunctionName]);
  } else if (Deno.args.includes("--print-json")) {
    console.log(JSON.stringify(digests));
  } else {
    const expected = renderFieldChatDeploymentIdentity(digests);
    if (Deno.args.includes("--write")) {
      await Deno.writeTextFile(GENERATED_IDENTITY_PATH, expected);
    } else if (Deno.args.includes("--check")) {
      const actual = await Deno.readTextFile(GENERATED_IDENTITY_PATH);
      if (actual !== expected) {
        throw new Error(
          "Field Chat deployment identity is stale; run the generator with --write",
        );
      }
    } else {
      throw new Error("Specify --check, --write, --print, or --print-json");
    }
  }
}
