import { join } from "node:path";
import { functionsRoot } from "./function_dependency_tools.ts";
import { computeFunctionBundleDigests } from "./function_bundle_identity.ts";

export const FIELD_CHAT_FUNCTION_NAMES = Object.freeze(
  [
    "explore-post-chat",
    "insight-chat",
    "species-dictionary-chat",
  ] as const,
);

export type FieldChatFunctionName = (typeof FIELD_CHAT_FUNCTION_NAMES)[number];

const GENERATED_IDENTITY_PATH = join(
  functionsRoot,
  "_shared",
  "fieldChatDeploymentIdentity.ts",
);
const HEX_DIGEST_PATTERN = /^[0-9a-f]{64}$/;

export async function computeFieldChatBundleDigests(): Promise<
  Readonly<Record<FieldChatFunctionName, string>>
> {
  return await computeFunctionBundleDigests(
    FIELD_CHAT_FUNCTION_NAMES,
    GENERATED_IDENTITY_PATH,
  );
}

export function renderFieldChatDeploymentIdentity(
  digests: Readonly<Record<FieldChatFunctionName, string>>,
): string {
  for (const functionName of FIELD_CHAT_FUNCTION_NAMES) {
    if (!HEX_DIGEST_PATTERN.test(digests[functionName])) {
      throw new Error(`Bundle digest is malformed for ${functionName}`);
    }
  }
  const entries = FIELD_CHAT_FUNCTION_NAMES.map((functionName) =>
    `    "${functionName}":\n      "${digests[functionName]}",`
  ).join("\n");
  return `// GENERATED by services/supabase/scripts/generate_field_chat_deployment_identity.ts.\n// Do not edit by hand. The generator excludes this file from its own digest.\n\nexport const FIELD_CHAT_BUNDLE_SHA256 = Object.freeze(\n  {\n${entries}\n  } as const,\n);\n\nexport type FieldChatDeploymentFunction = keyof typeof FIELD_CHAT_BUNDLE_SHA256;\n`;
}

function argumentValue(name: string): string | undefined {
  const index = Deno.args.indexOf(name);
  return index >= 0 ? Deno.args[index + 1] : undefined;
}

if (import.meta.main) {
  const digests = await computeFieldChatBundleDigests();
  const printFunction = argumentValue("--print");
  if (printFunction !== undefined) {
    if (
      !(FIELD_CHAT_FUNCTION_NAMES as readonly string[]).includes(
        printFunction,
      )
    ) {
      throw new Error(`Unknown Field Chat function: ${printFunction}`);
    }
    console.log(digests[printFunction as FieldChatFunctionName]);
  } else if (Deno.args.includes("--print-json")) {
    console.log(JSON.stringify(digests));
  } else {
    const expected = renderFieldChatDeploymentIdentity(digests);
    if (Deno.args.includes("--write")) {
      await Deno.writeTextFile(GENERATED_IDENTITY_PATH, expected);
    } else if (Deno.args.includes("--check")) {
      const actual = await Deno.readTextFile(GENERATED_IDENTITY_PATH);
      if (actual !== expected) {
        throw new Error(
          "Field Chat deployment identity is stale; run the generator with --write",
        );
      }
    } else {
      throw new Error("Specify --check, --write, --print, or --print-json");
    }
  }
}
