import { fingerprintJson } from "./identification_evaluation/evidence.ts";
import { requireCondition as check } from "./identification_evaluation/validation.ts";
import { deriveAIRequestId } from "../functions/_shared/aiQuota.ts";

const preparationPath = new URL(
  "../../../docs/rfcs/identification-evaluation-evidence/2026-09-23-audio-comparison-preparation/preparation.json",
  import.meta.url,
);
const outputPath = new URL(
  "../functions/identify-multimodal/comparison/plan.ts",
  import.meta.url,
);
const swiftOutputPath = new URL(
  "../../../apps/ios/Merian/Core/Network/Inference/DebugAudioComparisonPlan.generated.swift",
  import.meta.url,
);
const PREPARATION_SHA256 =
  "42350d978486e1a9edb409065be163b45f2d01d1182042b3e48f318e7ed43681";

/** Only the immutable reviewed six-clip preparation can supply this runtime table.
 * No environment, private owner configuration, source media or network access.
 * Changing a plan requires a new explicit preparation/version review.
 */
async function frozenPlan() {
  const text = await Deno.readTextFile(preparationPath);
  check(text.length <= 32_768);
  const preparation = JSON.parse(text);
  check(await fingerprintJson(preparation) === PREPARATION_SHA256);
  // The exact canonical digest establishes this artifact's reviewed schema.
  const assignments: {
    slot: number;
    caseId: string;
    arm: string;
    sourceWavSha256: string;
    sourceByteLength: number;
    processedWavSha256: string;
    providerRequestSha256: string;
    policySha256: string;
    confidenceSha256: string;
  }[] = preparation.assignments.map(
    (assignment: { caseId: string; arm: string }, index: number) => {
      const pair = preparation.pairs.find((p: { caseId: string }) =>
        p.caseId === assignment.caseId
      );
      const arm = pair.arms.find((a: { arm: string }) =>
        a.arm === assignment.arm
      );
      return {
        slot: index + 1,
        caseId: assignment.caseId,
        arm: arm.arm,
        sourceWavSha256: pair.sourceWavSha256,
        sourceByteLength: pair.sourceByteLength,
        processedWavSha256: arm.processedWavSha256,
        providerRequestSha256: arm.providerRequestSha256,
        policySha256: arm.policySha256,
        confidenceSha256: arm.confidenceSha256,
      };
    },
  );
  const plan = {
    version: 1,
    preparationSha256: PREPARATION_SHA256,
    assignments,
  };
  return { plan, digest: await fingerprintJson(plan) };
}

export async function renderAudioComparisonPlan(): Promise<string> {
  const { plan, digest } = await frozenPlan();
  const table = JSON.stringify(plan, null, 2).split("\n").map((line) => {
    // TypeScript formatting: trailing commas and SHA values on their own line.
    if (line.includes(":") && /"[0-9a-f]{64}"/.test(line)) {
      const [key, value] = line.split(": ");
      return `  ${key}:\n    ${line.match(/^ */)![0]}${
        value.endsWith(",") ? value : value + ","
      }`;
    }
    const next = /[0-9"}\]]$/.test(line) && line.trim() !== "{" && line !== "}"
      ? line + ","
      : line;
    return "  " + next;
  }).join("\n");
  return `// GENERATED by services/supabase/scripts/generate_audio_comparison_plan.ts.\n// Frozen source/arm/request bindings only; no runtime enablement or owner identity.\n\nexport const AUDIO_COMPARISON_PLAN_SHA256 =\n  "${digest}";\n\nexport const AUDIO_COMPARISON_PLAN = Object.freeze(\n${table} as const,\n);\n`;
}

export async function renderSwiftAudioComparisonPlan(): Promise<string> {
  // Both outputs derive from immutable preparation, even when repairing a stale
  // generated TS file. An imported runtime table would remain stale in memory.
  const { plan, digest } = await frozenPlan();
  const rows = await Promise.all(
    plan.assignments.map(async (a) => {
      const derived = await deriveAIRequestId(
        "ac0a0001-0000-8000-8000-000000000001",
        `${digest}:${a.slot}`,
      );
      const values = { ...a, scanId: "ac0a0001-" + derived.slice(9) };
      return `        DebugAudioComparisonAssignment(\n${
        Object.entries(values).map(([key, value]) =>
          `            ${key}: ${JSON.stringify(value)}`
        ).join(",\n")
      }\n        )`;
    }),
  );
  return `// GENERATED by services/supabase/scripts/generate_audio_comparison_plan.ts.
// Debug simulator only. Frozen bindings confer no server authorization.
#if DEBUG && targetEnvironment(simulator)
enum DebugAudioComparisonSlot: Int, CaseIterable, Sendable {
${plan.assignments.map((a) => `    case slot${a.slot} = ${a.slot}`).join("\n")}

    var assignment: DebugAudioComparisonAssignment {
        DebugAudioComparisonPlan.assignments[rawValue - 1]
    }
}

enum DebugAudioComparisonPlan {
    static let sha256 = "${digest}"
    static let assignments: [DebugAudioComparisonAssignment] = [
${rows.join(",\n")}
    ]
}
#endif
`;
}

if (import.meta.main) {
  if (Deno.args.length !== 1) throw new Error("specify_check_or_write");
  const rendered = await renderAudioComparisonPlan();
  if (Deno.args[0] === "--write") {
    await Deno.writeTextFile(outputPath, rendered);
    await Deno.writeTextFile(
      swiftOutputPath,
      await renderSwiftAudioComparisonPlan(),
    );
  } else if (Deno.args[0] === "--check") {
    if (await Deno.readTextFile(outputPath) !== rendered) {
      throw new Error("audio_comparison_plan_stale");
    }
    if (
      await Deno.readTextFile(swiftOutputPath) !==
        await renderSwiftAudioComparisonPlan()
    ) {
      throw new Error("native_audio_comparison_plan_stale");
    }
  } else throw new Error("specify_check_or_write");
}
