import { join } from "node:path";
import { functionsRoot } from "./function_dependency_tools.ts";
import { computeFunctionBundleDigests } from "./function_bundle_identity.ts";

const generatedPath = join(
  functionsRoot,
  "identify-multimodal",
  "deploymentIdentity.ts",
);

export async function identificationBundleDigest(): Promise<string> {
  return (await computeFunctionBundleDigests(
    ["identify-multimodal"],
    generatedPath,
  ))["identify-multimodal"];
}

export function renderIdentificationIdentity(digest: string): string {
  if (!/^[0-9a-f]{64}$/.test(digest)) throw new Error("invalid_bundle_digest");
  return `// GENERATED by services/supabase/scripts/generate_identification_deployment_identity.ts.\n// Excludes this file from its own runtime-graph digest. Not a Git revision.\n\nexport const IDENTIFICATION_BUNDLE_SHA256 =\n  "${digest}";\n`;
}

if (import.meta.main) {
  const rendered = renderIdentificationIdentity(
    await identificationBundleDigest(),
  );
  if (Deno.args.length !== 1) throw new Error("specify_check_or_write");
  if (Deno.args[0] === "--write") {
    await Deno.writeTextFile(generatedPath, rendered);
  } else if (Deno.args[0] === "--check") {
    if (await Deno.readTextFile(generatedPath) !== rendered) {
      throw new Error(
        "identification_bundle_identity_stale_run_generator_with_write",
      );
    }
  } else throw new Error("specify_check_or_write");
}
