import { fingerprintJson } from "./identification_evaluation/evidence.ts";
import { requireCondition as check } from "./identification_evaluation/validation.ts";
import { deriveAIRequestId } from "../functions/_shared/aiQuota.ts";
import type { AudioUncertaintyPreparation } from "./prepare_audio_uncertainty_comparison.ts";

const preparationPath = new URL(
  "../../../docs/rfcs/identification-evaluation-evidence/2026-09-24-audio-uncertainty-preparation/preparation.json",
  import.meta.url,
);
const outputPath = new URL(
  "../functions/identify-multimodal/comparison/promptPlan.ts",
  import.meta.url,
);
const swiftOutputPath = new URL(
  "../../../apps/ios/Merian/Core/Network/Inference/DebugAudioPromptComparisonPlan.generated.swift",
  import.meta.url,
);
export const AUDIO_PROMPT_PREPARATION_SHA256 =
  "068f74f51f4e7c81a2eaae36f1f51363e84fa57e5f4dadf6694e007fe1fb63bb";

/** The reviewed immutable preparation is the only source, never caller input. */
async function frozenPlan() {
  const text = await Deno.readTextFile(preparationPath);
  check(text.length <= 131072);
  const value: unknown = JSON.parse(text);
  check(await fingerprintJson(value) === AUDIO_PROMPT_PREPARATION_SHA256);
  // Exact reviewed digest establishes this version's full shape.
  const preparation = value as AudioUncertaintyPreparation;
  const assignments = preparation.assignments.map((slot) => {
    const pair = preparation.pairs.find((p) => p.caseId === slot.caseId)!;
    const arm = pair.arms.find((a) => a.arm === slot.arm)!;
    return {
      slot: slot.slot,
      block: slot.block,
      repeat: slot.repeat,
      caseId: slot.caseId,
      arm: slot.arm,
      sourceWavSha256: pair.sourceWavSha256,
      sourceByteLength: pair.sourceByteLength,
      processedWavSha256: pair.processedWavSha256,
      providerRequestSha256: arm.providerRequestSha256,
      policySha256: arm.policySha256,
      confidenceSha256: arm.confidenceSha256,
    };
  });
  const plan = {
    version: 1,
    preparationSha256: AUDIO_PROMPT_PREPARATION_SHA256,
    designSha256: preparation.designSha256,
    startsNotBefore: preparation.preparedAt,
    expiresNotAfter: preparation.retentionThrough + "T00:00:00.000Z",
    assignments,
  };
  return { plan, digest: await fingerprintJson(plan) };
}

export async function renderAudioPromptComparisonPlan(): Promise<string> {
  const { plan, digest } = await frozenPlan();
  const table = JSON.stringify(plan, null, 2).split("\n").map((line) => {
    if (line.includes(":") && /"[0-9a-f]{64}"/.test(line)) {
      const [key, value] = line.split(": ");
      return "  " + key + ":\n    " + line.match(/^ */)![0] +
        (value.endsWith(",") ? value : value + ",");
    }
    const next = /[0-9"}\]]$/.test(line) && line.trim() !== "{" && line !== "}"
      ? line + ","
      : line;
    return "  " + next;
  }).join("\n");
  return "// GENERATED by services/supabase/scripts/generate_audio_prompt_comparison_plan.ts.\n" +
    "// Frozen prompt experiment only; no enablement or owner identity.\n\n" +
    'export const AUDIO_PROMPT_COMPARISON_PLAN_SHA256 =\n  "' + digest +
    '";\n\n' +
    "export const AUDIO_PROMPT_COMPARISON_PLAN = Object.freeze(\n" + table +
    " as const,\n);\n";
}

export async function renderSwiftAudioPromptComparisonPlan(): Promise<string> {
  const { plan, digest } = await frozenPlan();
  const rows = await Promise.all(plan.assignments.map(async (a) => {
    const id = await deriveAIRequestId(
      "ac0b0001-0000-8000-8000-000000000001",
      digest + ":" + a.slot,
    );
    const { repeat: repeatIndex, ...assignment } = a;
    const values = {
      slot: assignment.slot,
      block: assignment.block,
      repeatIndex,
      ...Object.fromEntries(
        Object.entries(assignment).filter(([key]) =>
          key !== "slot" && key !== "block"
        ),
      ),
      scanId: "ac0b0001-" + id.slice(9),
    };
    return "        DebugAudioPromptComparisonAssignment(\n" +
      Object.entries(values).map(([key, value]) =>
        "            " + key + ": " + JSON.stringify(value)
      ).join(",\n") + "\n        )";
  }));
  return "// GENERATED by services/supabase/scripts/generate_audio_prompt_comparison_plan.ts.\n" +
    "// Debug simulator only. Frozen bindings confer no server authorization.\n" +
    "#if DEBUG && targetEnvironment(simulator)\n" +
    "enum DebugAudioPromptComparisonSlot: Int, CaseIterable, Sendable {\n" +
    plan.assignments.map((a) => "    case slot" + a.slot + " = " + a.slot).join(
      "\n",
    ) +
    "\n\n    var assignment: DebugAudioPromptComparisonAssignment {\n" +
    "        DebugAudioPromptComparisonPlan.assignments[rawValue - 1]\n    }\n}\n\n" +
    "enum DebugAudioPromptComparisonPlan {\n    static let sha256 = " +
    JSON.stringify(digest) +
    "\n    static let assignments: [DebugAudioPromptComparisonAssignment] = [\n" +
    rows.join(",\n") + "\n    ]\n}\n#endif\n";
}
if (import.meta.main) {
  check(
    Deno.args.length === 1 && ["--write", "--check"].includes(Deno.args[0]),
  );
  for (
    const [path, rendered] of [
      [outputPath, await renderAudioPromptComparisonPlan()],
      [swiftOutputPath, await renderSwiftAudioPromptComparisonPlan()],
    ] as const
  ) {
    if (Deno.args[0] === "--write") await Deno.writeTextFile(path, rendered);
    else check(await Deno.readTextFile(path) === rendered);
  }
}
