// GENERATED by services/supabase/scripts/generate_audio_prompt_comparison_plan.ts.
// Debug simulator only. Frozen bindings confer no server authorization.
#if DEBUG && targetEnvironment(simulator)
enum DebugAudioPromptComparisonSlot: Int, CaseIterable, Sendable {
    case slot1 = 1
    case slot2 = 2
    case slot3 = 3
    case slot4 = 4
    case slot5 = 5
    case slot6 = 6
    case slot7 = 7
    case slot8 = 8
    case slot9 = 9
    case slot10 = 10
    case slot11 = 11
    case slot12 = 12
    case slot13 = 13
    case slot14 = 14
    case slot15 = 15
    case slot16 = 16
    case slot17 = 17
    case slot18 = 18
    case slot19 = 19
    case slot20 = 20
    case slot21 = 21
    case slot22 = 22
    case slot23 = 23
    case slot24 = 24
    case slot25 = 25
    case slot26 = 26
    case slot27 = 27
    case slot28 = 28
    case slot29 = 29
    case slot30 = 30
    case slot31 = 31
    case slot32 = 32
    case slot33 = 33
    case slot34 = 34
    case slot35 = 35
    case slot36 = 36

    var assignment: DebugAudioPromptComparisonAssignment {
        DebugAudioPromptComparisonPlan.assignments[rawValue - 1]
    }
}

enum DebugAudioPromptComparisonPlan {
    static let sha256 = "8019602955455d8c8fb83ff368a1e54a6dfee58e1f4680f801e45bcee30d8dee"
    static let assignments: [DebugAudioPromptComparisonAssignment] = [
        DebugAudioPromptComparisonAssignment(
            slot: 1,
            block: 1,
            repeatIndex: 1,
            caseId: "c0025",
            arm: "A",
            sourceWavSha256: "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
            sourceByteLength: 882044,
            processedWavSha256: "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
            providerRequestSha256: "94899b80e308bb14ef1e096dfb23b55d77252bd913d6abb3bf6f65b4fe133add",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-8287-8e82-a8ce-2e650caccb24"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 2,
            block: 1,
            repeatIndex: 1,
            caseId: "c0025",
            arm: "B",
            sourceWavSha256: "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
            sourceByteLength: 882044,
            processedWavSha256: "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
            providerRequestSha256: "0db615a433e790bec42ae0b7d90b2a59c4c122c3045bd8ba4b130f997fea8051",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-5d05-8491-9d91-151a9eff3ce9"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 3,
            block: 1,
            repeatIndex: 1,
            caseId: "c0020",
            arm: "B",
            sourceWavSha256: "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
            sourceByteLength: 285740,
            processedWavSha256: "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
            providerRequestSha256: "113fcd3b483e50ac40145ed4a3e967e80ad1d1577883041511e1e8cc80afbed4",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-b91d-82e8-9d46-f0237019a2a8"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 4,
            block: 1,
            repeatIndex: 1,
            caseId: "c0020",
            arm: "A",
            sourceWavSha256: "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
            sourceByteLength: 285740,
            processedWavSha256: "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
            providerRequestSha256: "abf7806787686c8d993739d7944a462638b9ef1b2bf0e21e548c52ea85ba1981",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-3ac2-8133-8196-5429e2615678"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 5,
            block: 1,
            repeatIndex: 1,
            caseId: "c0023",
            arm: "A",
            sourceWavSha256: "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
            sourceByteLength: 437804,
            processedWavSha256: "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
            providerRequestSha256: "d4ec0894f5b693bc3428a3fe4f04232514088bbfd6e35e1f889d96cff5c71783",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-0898-86b8-aa74-d31d8ad84969"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 6,
            block: 1,
            repeatIndex: 1,
            caseId: "c0023",
            arm: "B",
            sourceWavSha256: "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
            sourceByteLength: 437804,
            processedWavSha256: "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
            providerRequestSha256: "53645173f1f8cee4927508b34392e5f79abdc9a759d263370df0bdce098cc191",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-3434-8ebc-a90b-de0778b07498"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 7,
            block: 1,
            repeatIndex: 1,
            caseId: "c0026",
            arm: "B",
            sourceWavSha256: "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
            sourceByteLength: 478440,
            processedWavSha256: "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
            providerRequestSha256: "e54017a1d6d1805f9b824e9b58c1753aa6bc8d41f0f5c4d7d1a58f2b0dff10b3",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-d378-834c-8a4b-3f2acfc9c383"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 8,
            block: 1,
            repeatIndex: 1,
            caseId: "c0026",
            arm: "A",
            sourceWavSha256: "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
            sourceByteLength: 478440,
            processedWavSha256: "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
            providerRequestSha256: "7f7e493c1129d36646006d2d42ea30d5a5124c699f0ff5d8f95bfea96f27aa07",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-cbff-8435-bf81-c5c95ff6c589"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 9,
            block: 1,
            repeatIndex: 1,
            caseId: "c0021",
            arm: "A",
            sourceWavSha256: "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
            sourceByteLength: 875564,
            processedWavSha256: "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
            providerRequestSha256: "ba7ce5caea5ce5ae8badb2655d2ad1f092b0f62ff2ddcdab16ea47a63f6fbb19",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-5400-8c6c-9293-3581253d6c9f"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 10,
            block: 1,
            repeatIndex: 1,
            caseId: "c0021",
            arm: "B",
            sourceWavSha256: "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
            sourceByteLength: 875564,
            processedWavSha256: "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
            providerRequestSha256: "a148c514aacff358eeda4d665ac5b2b61d21580da06aae68b64c723b96cac83a",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-6cee-8a4e-9fce-0c61cc5562d0"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 11,
            block: 1,
            repeatIndex: 1,
            caseId: "c0024",
            arm: "B",
            sourceWavSha256: "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
            sourceByteLength: 476972,
            processedWavSha256: "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
            providerRequestSha256: "566428c0cf6498ceef36749fb79b973a5a9958d261072245f8590f4f51c3a89a",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-49a1-8752-9a27-55075f3d07e7"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 12,
            block: 1,
            repeatIndex: 1,
            caseId: "c0024",
            arm: "A",
            sourceWavSha256: "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
            sourceByteLength: 476972,
            processedWavSha256: "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
            providerRequestSha256: "c4fb287be8f29fd3217918524f45297609b19294132d064f7f0c3604041d8e6e",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-c638-8258-8a03-382fa294c5a3"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 13,
            block: 2,
            repeatIndex: 2,
            caseId: "c0023",
            arm: "B",
            sourceWavSha256: "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
            sourceByteLength: 437804,
            processedWavSha256: "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
            providerRequestSha256: "53645173f1f8cee4927508b34392e5f79abdc9a759d263370df0bdce098cc191",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-c97d-8b4f-96bc-a038ea7767e7"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 14,
            block: 2,
            repeatIndex: 2,
            caseId: "c0023",
            arm: "A",
            sourceWavSha256: "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
            sourceByteLength: 437804,
            processedWavSha256: "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
            providerRequestSha256: "d4ec0894f5b693bc3428a3fe4f04232514088bbfd6e35e1f889d96cff5c71783",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-390b-8c10-bd0e-044851b924f4"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 15,
            block: 2,
            repeatIndex: 2,
            caseId: "c0026",
            arm: "A",
            sourceWavSha256: "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
            sourceByteLength: 478440,
            processedWavSha256: "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
            providerRequestSha256: "7f7e493c1129d36646006d2d42ea30d5a5124c699f0ff5d8f95bfea96f27aa07",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-b816-8198-85d3-fbf5450ec6d2"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 16,
            block: 2,
            repeatIndex: 2,
            caseId: "c0026",
            arm: "B",
            sourceWavSha256: "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
            sourceByteLength: 478440,
            processedWavSha256: "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
            providerRequestSha256: "e54017a1d6d1805f9b824e9b58c1753aa6bc8d41f0f5c4d7d1a58f2b0dff10b3",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-07bb-8c80-895a-6b0281c05828"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 17,
            block: 2,
            repeatIndex: 2,
            caseId: "c0021",
            arm: "B",
            sourceWavSha256: "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
            sourceByteLength: 875564,
            processedWavSha256: "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
            providerRequestSha256: "a148c514aacff358eeda4d665ac5b2b61d21580da06aae68b64c723b96cac83a",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-0ad7-8b7d-81df-310c37a77628"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 18,
            block: 2,
            repeatIndex: 2,
            caseId: "c0021",
            arm: "A",
            sourceWavSha256: "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
            sourceByteLength: 875564,
            processedWavSha256: "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
            providerRequestSha256: "ba7ce5caea5ce5ae8badb2655d2ad1f092b0f62ff2ddcdab16ea47a63f6fbb19",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-af91-8336-8d9e-9e04ae190e12"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 19,
            block: 2,
            repeatIndex: 2,
            caseId: "c0024",
            arm: "A",
            sourceWavSha256: "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
            sourceByteLength: 476972,
            processedWavSha256: "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
            providerRequestSha256: "c4fb287be8f29fd3217918524f45297609b19294132d064f7f0c3604041d8e6e",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-43fa-8184-8d22-4854efd923ee"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 20,
            block: 2,
            repeatIndex: 2,
            caseId: "c0024",
            arm: "B",
            sourceWavSha256: "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
            sourceByteLength: 476972,
            processedWavSha256: "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
            providerRequestSha256: "566428c0cf6498ceef36749fb79b973a5a9958d261072245f8590f4f51c3a89a",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-ea17-8c91-a4d2-49b63b75c837"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 21,
            block: 2,
            repeatIndex: 2,
            caseId: "c0025",
            arm: "B",
            sourceWavSha256: "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
            sourceByteLength: 882044,
            processedWavSha256: "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
            providerRequestSha256: "0db615a433e790bec42ae0b7d90b2a59c4c122c3045bd8ba4b130f997fea8051",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-bb60-8c2a-92ca-4d1b12595da1"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 22,
            block: 2,
            repeatIndex: 2,
            caseId: "c0025",
            arm: "A",
            sourceWavSha256: "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
            sourceByteLength: 882044,
            processedWavSha256: "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
            providerRequestSha256: "94899b80e308bb14ef1e096dfb23b55d77252bd913d6abb3bf6f65b4fe133add",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-4992-8290-aef1-030409fbd7ee"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 23,
            block: 2,
            repeatIndex: 2,
            caseId: "c0020",
            arm: "A",
            sourceWavSha256: "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
            sourceByteLength: 285740,
            processedWavSha256: "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
            providerRequestSha256: "abf7806787686c8d993739d7944a462638b9ef1b2bf0e21e548c52ea85ba1981",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-0f2a-8fb2-9dd2-214195f66778"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 24,
            block: 2,
            repeatIndex: 2,
            caseId: "c0020",
            arm: "B",
            sourceWavSha256: "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
            sourceByteLength: 285740,
            processedWavSha256: "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
            providerRequestSha256: "113fcd3b483e50ac40145ed4a3e967e80ad1d1577883041511e1e8cc80afbed4",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-80a7-8779-9de7-eca4276b8bc2"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 25,
            block: 3,
            repeatIndex: 3,
            caseId: "c0021",
            arm: "A",
            sourceWavSha256: "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
            sourceByteLength: 875564,
            processedWavSha256: "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
            providerRequestSha256: "ba7ce5caea5ce5ae8badb2655d2ad1f092b0f62ff2ddcdab16ea47a63f6fbb19",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-4727-8c69-85f3-f2af35fadab5"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 26,
            block: 3,
            repeatIndex: 3,
            caseId: "c0021",
            arm: "B",
            sourceWavSha256: "196789a6a6344ebff689c1847b88a29a1babda5d5485c17c1161ca7e949a9739",
            sourceByteLength: 875564,
            processedWavSha256: "82a45978b1d42e57c5780232d4131345bb48c069085f2ed0bd61cf6f8bee3769",
            providerRequestSha256: "a148c514aacff358eeda4d665ac5b2b61d21580da06aae68b64c723b96cac83a",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-dbbd-866a-87b9-889cf00e5b0d"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 27,
            block: 3,
            repeatIndex: 3,
            caseId: "c0024",
            arm: "B",
            sourceWavSha256: "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
            sourceByteLength: 476972,
            processedWavSha256: "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
            providerRequestSha256: "566428c0cf6498ceef36749fb79b973a5a9958d261072245f8590f4f51c3a89a",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-32d9-817d-ab4f-3842071e859a"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 28,
            block: 3,
            repeatIndex: 3,
            caseId: "c0024",
            arm: "A",
            sourceWavSha256: "694d5a5feaafe50c9147b9d2249ab59e710935efb99d16c09001af8787464c60",
            sourceByteLength: 476972,
            processedWavSha256: "65f15be292427e349694122a12980b8219883fc632b1c3823844b265b6bf470a",
            providerRequestSha256: "c4fb287be8f29fd3217918524f45297609b19294132d064f7f0c3604041d8e6e",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-dc6e-8726-ba93-b4310b7cf471"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 29,
            block: 3,
            repeatIndex: 3,
            caseId: "c0025",
            arm: "A",
            sourceWavSha256: "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
            sourceByteLength: 882044,
            processedWavSha256: "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
            providerRequestSha256: "94899b80e308bb14ef1e096dfb23b55d77252bd913d6abb3bf6f65b4fe133add",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-b422-8918-a3e2-0743a030d79a"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 30,
            block: 3,
            repeatIndex: 3,
            caseId: "c0025",
            arm: "B",
            sourceWavSha256: "5a35dc6ad96f1b905a7eca55d71e8efb39a1af8fa1617c0d3dcdccd362dcaada",
            sourceByteLength: 882044,
            processedWavSha256: "835546ab87f317a09eb34cf928799a8a44360c2285b850cb7ad46e65394e0357",
            providerRequestSha256: "0db615a433e790bec42ae0b7d90b2a59c4c122c3045bd8ba4b130f997fea8051",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-878f-81a7-8cc2-2ee3abdfc670"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 31,
            block: 3,
            repeatIndex: 3,
            caseId: "c0020",
            arm: "B",
            sourceWavSha256: "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
            sourceByteLength: 285740,
            processedWavSha256: "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
            providerRequestSha256: "113fcd3b483e50ac40145ed4a3e967e80ad1d1577883041511e1e8cc80afbed4",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-80c8-8277-b396-7d43e5090580"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 32,
            block: 3,
            repeatIndex: 3,
            caseId: "c0020",
            arm: "A",
            sourceWavSha256: "6b5e9e6cc45d16a80980386541649b1ce9fcd94cf3ad54a49d37cf0fd6e3ed67",
            sourceByteLength: 285740,
            processedWavSha256: "410e61df41cdf01359865e8aa48663bd078a6411a8b1e24d561ac9de1d468829",
            providerRequestSha256: "abf7806787686c8d993739d7944a462638b9ef1b2bf0e21e548c52ea85ba1981",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-d4af-88aa-8ae9-63454606858e"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 33,
            block: 3,
            repeatIndex: 3,
            caseId: "c0023",
            arm: "A",
            sourceWavSha256: "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
            sourceByteLength: 437804,
            processedWavSha256: "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
            providerRequestSha256: "d4ec0894f5b693bc3428a3fe4f04232514088bbfd6e35e1f889d96cff5c71783",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-a9c6-8873-a3d5-6c015aea8d61"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 34,
            block: 3,
            repeatIndex: 3,
            caseId: "c0023",
            arm: "B",
            sourceWavSha256: "4ee517d08701c5f7cebd4a9b7c2f4029351f72fb079cbbb72106dd2d04f51a0f",
            sourceByteLength: 437804,
            processedWavSha256: "12d57d18a270203f3765cddc3312666892c7c1e5169ce451b24eca0a1d005bbb",
            providerRequestSha256: "53645173f1f8cee4927508b34392e5f79abdc9a759d263370df0bdce098cc191",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-3007-8822-8ca1-142950c9f099"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 35,
            block: 3,
            repeatIndex: 3,
            caseId: "c0026",
            arm: "B",
            sourceWavSha256: "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
            sourceByteLength: 478440,
            processedWavSha256: "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
            providerRequestSha256: "e54017a1d6d1805f9b824e9b58c1753aa6bc8d41f0f5c4d7d1a58f2b0dff10b3",
            policySha256: "94f77589a88761829b0146592ba1e5c6db5acd44b9b85a0fca86e9cc71876530",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-a65b-860d-bf9d-c4eaaaf73a97"
        ),
        DebugAudioPromptComparisonAssignment(
            slot: 36,
            block: 3,
            repeatIndex: 3,
            caseId: "c0026",
            arm: "A",
            sourceWavSha256: "6f4cd19d980986aceff21efa656a6b17ba993bfe5d5363967530c4add3de316d",
            sourceByteLength: 478440,
            processedWavSha256: "45a24bf83c11d027013ddbb0d61c3d7748ab992ba11c0c0e859163fdccafa23a",
            providerRequestSha256: "7f7e493c1129d36646006d2d42ea30d5a5124c699f0ff5d8f95bfea96f27aa07",
            policySha256: "83000ad1bbcb2912c61a4d29a60c77b382f78150a464640f7c757e5c1a896f39",
            confidenceSha256: "7994954960f1355f6f0fe520ad2f5a6552fb3785f6bd900661ff48abae85fdcf",
            scanId: "ac0b0001-ed63-80dc-a2e9-d6bdfdfe3ad8"
        )
    ]
}
#endif
