// GENERATED by services/supabase/scripts/generate_identification_deployment_identity.ts.
// Excludes this file from its own runtime-graph digest. Not a Git revision.

export const IDENTIFICATION_BUNDLE_SHA256 =
  "1949f9c56f0bfa70378adf2f35d8a7275effeeb34c2d6a3afad7bae91f8ad9dd";
