// GENERATED by services/supabase/scripts/generate_identification_deployment_identity.ts.
// Excludes this file from its own runtime-graph digest. Not a Git revision.

export const IDENTIFICATION_BUNDLE_SHA256 =
  "00de0f7ed1724f5e349004fac500c690e72a70e4b77ca609e22a6592cfec1da5";
