// GENERATED by services/supabase/scripts/generate_identification_deployment_identity.ts.
// Excludes this file from its own runtime-graph digest. Not a Git revision.

export const IDENTIFICATION_BUNDLE_SHA256 =
  "559d76004dbbedd49829c6f586fe23debbdadd70246e3eb469d9d66f8f8c2df2";
