#!/usr/bin/env python3
"""
freeze_schema.py
Generates a frozen @Model class snapshot for SchemaV{N}.swift by reading the current
ActiveSchema/LocalScanRecord.swift and stripping public access modifiers.

Run this as STEP 1 of the schema update workflow (see schema_update.md) — BEFORE modifying
any global model in ActiveSchema/. The snapshot must capture the model shape as it exists NOW.

Usage:
    python3 .agents/workflows/freeze_schema.py <version>             # print to stdout
    python3 .agents/workflows/freeze_schema.py <version> --apply     # append to SchemaV{N}.swift

Example:
    python3 .agents/workflows/freeze_schema.py 28             # preview the frozen snapshot
    python3 .agents/workflows/freeze_schema.py 28 --apply     # append it to SchemaV28.swift

The --apply flag appends the snapshot to the schema file and prints next-step instructions.
Always review the generated code before committing — verify no fields were missed.
"""
import sys
import re
import os


def extract_model_class(source_path: str) -> list[str]:
    """Read source_path, find the @Model class, return lines with public modifiers stripped."""
    with open(source_path) as f:
        lines = f.readlines()

    # Find the @Model decorator line
    model_idx = None
    for i, line in enumerate(lines):
        if line.strip() == "@Model":
            model_idx = i
            break

    if model_idx is None:
        raise ValueError(f"No bare '@Model' decorator found in {source_path}")

    # Collect from @Model to the matching closing brace (handles nested braces in init body)
    collected = []
    brace_depth = 0
    started = False

    for i in range(model_idx, len(lines)):
        raw = lines[i].rstrip("\n")
        collected.append(raw)
        brace_depth += raw.count("{") - raw.count("}")
        if brace_depth > 0:
            started = True
        if started and brace_depth <= 0:
            break

    if not started:
        raise ValueError(f"Could not find class body in {source_path}")

    # Strip `public ` modifiers (preserves @Attribute, originalName, etc.)
    result = []
    for line in collected:
        cleaned = re.sub(r"\bpublic\s+", "", line)
        result.append(cleaned)

    return result


def wrap_in_extension(version: str, class_lines: list[str]) -> str:
    """Wrap the class lines in extension MerianSchemaV{version} { ... }."""
    output_lines = [f"extension MerianSchemaV{version} {{"]
    for line in class_lines:
        # Add 4-space indent for the extension body; preserve blank lines
        output_lines.append("    " + line if line.strip() else "")
    output_lines.append("}")
    return "\n".join(output_lines)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: freeze_schema.py <version> [--apply]", file=sys.stderr)
        print("Example: freeze_schema.py 28", file=sys.stderr)
        sys.exit(1)

    version = sys.argv[1]
    apply = "--apply" in sys.argv

    # Locate project root (this script lives at <root>/.agents/workflows/)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(os.path.dirname(script_dir))

    source_file = os.path.join(root_dir, "merian/Models/ActiveSchema/LocalScanRecord.swift")
    target_file = os.path.join(root_dir, f"merian/Models/Schema/SchemaV{version}.swift")

    if not os.path.exists(source_file):
        print(f"Error: {source_file} not found.", file=sys.stderr)
        sys.exit(1)

    if apply and not os.path.exists(target_file):
        print(
            f"Error: {target_file} does not exist. Create the schema file first.",
            file=sys.stderr,
        )
        sys.exit(1)

    class_lines = extract_model_class(source_file)
    snapshot = wrap_in_extension(version, class_lines)

    header = (
        f"// MARK: - Frozen LocalScanRecord snapshot for MerianSchemaV{version}\n"
        f"// Generated by: python3 .agents/workflows/freeze_schema.py {version}\n"
        f"// Captures the LocalScanRecord shape AT V{version} — before any new fields were added.\n"
        f"// DO NOT modify after committing. Checksums must remain stable forever.\n"
    )

    output = "\n" + header + snapshot + "\n"

    if apply:
        with open(target_file, "a") as f:
            f.write(output)
        print(f"Frozen LocalScanRecord appended to SchemaV{version}.swift")
        print()
        print("Next steps:")
        print(f"  1. Open SchemaV{version}.swift and verify the snapshot — no missing fields.")
        print(f"  2. Update `models` to use MerianSchemaV{version}.LocalScanRecord.self")
        print(f"  3. Add typealiases for unchanged models (ScanCollection, OfflineQueuedScan,")
        print(f"     PendingCloudDeletionTask) pointing to their previous version's types.")
        print(f"     If ScanCollection changed, add a frozen snapshot in the enum body instead.")
        print(f"  4. Build: xcodebuild build -scheme Merian \\")
        print(f"         -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0'")
        print(f"  5. Only after a clean build: modify ActiveSchema/LocalScanRecord.swift")
    else:
        print(output)
        print(f"# Paste the above into SchemaV{version}.swift (before modifying ActiveSchema/), then:")
        print(f"#   1. Update `models` to use MerianSchemaV{version}.LocalScanRecord.self")
        print(f"#   2. Add typealiases for unchanged models")
        print(f"#   3. xcodebuild build to verify — must pass before touching ActiveSchema/")


if __name__ == "__main__":
    main()
