import Foundation
import SwiftData

// Added in V35:
//   LocalScanRecord.confirmedSpeciesId — String?
//     Stores the authoritative Species ID when a user confirms or overrides an AI prediction.
//
// NOTE: References global model types — freeze when V36 is created.
enum MerianSchemaV35: VersionedSchema {
    static var versionIdentifier = Schema.Version(35, 0, 0)

    static var models: [any PersistentModel.Type] {
        [MerianSchemaV35.LocalScanRecord.self, OfflineQueuedScan.self,
         ScanCollection.self, PendingCloudDeletionTask.self,
         UserSpeciesPreference.self]
    }

    typealias OfflineQueuedScan = MerianSchemaV34.OfflineQueuedScan
    typealias ScanCollection = MerianSchemaV31.ScanCollection
    typealias PendingCloudDeletionTask = MerianSchemaV30.PendingCloudDeletionTask
    typealias UserSpeciesPreference = MerianSchemaV34.UserSpeciesPreference

    // MARK: - Frozen LocalScanRecord snapshot for MerianSchemaV35
    // Generated by: python3 .agents/workflows/freeze_schema.py 35
    // Captures the LocalScanRecord shape AT V35 — before any new fields were added.
    // DO NOT modify after committing. Checksums must remain stable forever.
    @Model
    final class LocalScanRecord {
        @Attribute(.unique) var id: String
        var speciesId: String
        var scientificName: String
        var commonName: String
        var timestamp: Date
        var captureDate: Date?
        var localImagePath: String?

        var semanticTags: [String]
        /// Hazard classification returned by the AI. One of: "none" | "poisonous" | "venomous" | "allergenic" | "irritant".
        var hazardType: String = "none"
        var isBiological: Bool
        var isLiveCapture: Bool
        var isInvasive: Bool
        var ecologyType: String
        var wikipediaUrl: String?
        /// Wikipedia summary paragraph for this species. Cached from the Wikipedia REST API.
        @Attribute(originalName: "wikipediaExtract") var wikipediaOverview: String?
        var referenceImageUrl: String?
        var additionalImagePaths: [String]?
        var confidenceScore: Double?
        @Attribute var isLocallyArchived: Bool = false

        var taxonomyKingdom: String?
        var taxonomyPhylum: String?
        var taxonomyClass: String?
        var taxonomyOrder: String?
        var taxonomyFamily: String?
        var taxonomyGenus: String?

        var locationName: String?
        var weatherCondition: String?
        var weatherTemperatureF: Double?

        var collections: [ScanCollection]? = []

        var similarSpecies: [String]?
        var lookalikesData: Data?
        /// JSON-encoded `[IdentificationCandidate]` — the model's top alternative species when
        /// `confidenceScore` fell below the tier-specific `MerianConfig.diagnosticTrigger` threshold.
        /// Nil for high-confidence scans and all scans captured before V28.
        @Attribute var candidatesData: Data?

        /// Scientific name chosen by the user when they disagreed with the AI's identification.
        /// Nil means no override — AI identification accepted by default. Cloud-synced.
        @Attribute var userIdentificationOverride: String?
        /// Local-only flag set when user taps "Yes, correct" on the CandidatesCard prompt.
        /// Suppresses the "Was the AI correct?" prompt on re-open. Not synced to cloud.
        @Attribute var userConfirmedIdentification: Bool = false

        /// Set to true when the user flags an identification for manual moderation review.
        /// Retains the "Under Review" state across app sessions locally.
        @Attribute var isFlagged: Bool = false

        @Attribute var iucnRedListStatus: String?
        @Attribute var gpsLatitude: Double?
        @Attribute var gpsLongitude: Double?
        @Attribute var gpsElevation: Double?
        @Attribute var zoomFactor: Double?

        /// Per-scan AI vision reasoning — unique to the specific photo submitted.
        @Attribute var aiReasoning: String?
        @Attribute var habitatDescription: String?
        /// GBIF species usage key for occurrence density heatmap tiles.
        @Attribute var gbifTaxonKey: Int?

        @Attribute var estimatedSizeCm: Double?
        @Attribute var lifeStage: String?
        @Attribute var reproductiveCondition: String?
        @Attribute var individualCount: Int?
        @Attribute var ecologicalInteractions: [String]?
        @Attribute var inferenceTier: String?

        /// User-defined custom tags for personal categorization and search indexing.
        @Attribute var customTags: [String] = []

        /// Tracks if a user has opened the scan's insight sheet. Defaults to true so historic scans don't receive "New" badges.
        var hasBeenViewed: Bool = true

        /// Gemini's photographic quality score (0–100) for the submitted image.
        /// Derived from `image_quality.overall_score` in the edge response.
        /// Nil for scans captured before V30.
        @Attribute var imageQualityScore: Int?

        /// All known English vernacular synonyms beyond `commonName`.
        /// Sourced from GBIF vernacular names during background enrichment.
        /// Nil for scans captured before V34 or species not yet enriched.
        @Attribute var alternativeCommonNames: [String]?

        @Attribute var confirmedSpeciesId: String?

        init(
            id: String = UUID().uuidString,
            speciesId: String,
            scientificName: String,
            commonName: String,
            timestamp: Date = Date(),
            captureDate: Date? = nil,
            localImagePath: String? = nil,
            semanticTags: [String] = [],
            hazardType: String = "none",
            isBiological: Bool = true,
            isLiveCapture: Bool = true,
            isInvasive: Bool = false,
            ecologyType: String = "unknown",
            wikipediaUrl: String? = nil,
            wikipediaOverview: String? = nil,
            referenceImageUrl: String? = nil,
            additionalImagePaths: [String]? = nil,
            confidenceScore: Double? = nil,
            isLocallyArchived: Bool = false,
            taxonomyKingdom: String? = nil,
            taxonomyPhylum: String? = nil,
            taxonomyClass: String? = nil,
            taxonomyOrder: String? = nil,
            taxonomyFamily: String? = nil,
            taxonomyGenus: String? = nil,
            locationName: String? = nil,
            weatherCondition: String? = nil,
            weatherTemperatureF: Double? = nil,
            collections: [ScanCollection]? = [],
            similarSpecies: [String]? = nil,
            lookalikesData: Data? = nil,
            candidatesData: Data? = nil,
            iucnRedListStatus: String? = nil,
            gpsLatitude: Double? = nil,
            gpsLongitude: Double? = nil,
            gpsElevation: Double? = nil,
            zoomFactor: Double? = nil,
            aiReasoning: String? = nil,
            habitatDescription: String? = nil,
            gbifTaxonKey: Int? = nil,
            estimatedSizeCm: Double? = nil,
            lifeStage: String? = nil,
            reproductiveCondition: String? = nil,
            individualCount: Int? = nil,
            ecologicalInteractions: [String]? = nil,
            inferenceTier: String? = nil,
            customTags: [String] = [],
            hasBeenViewed: Bool = false,
            userIdentificationOverride: String? = nil,
            userConfirmedIdentification: Bool = false,
            isFlagged: Bool = false,
            imageQualityScore: Int? = nil,
            alternativeCommonNames: [String]? = nil,
            confirmedSpeciesId: String? = nil) {

            self.id = id
            self.speciesId = speciesId
            self.scientificName = scientificName
            self.commonName = commonName
            self.timestamp = timestamp
            self.captureDate = captureDate
            self.localImagePath = localImagePath
            self.semanticTags = semanticTags
            self.hazardType = hazardType
            self.isBiological = isBiological
            self.isLiveCapture = isLiveCapture
            self.isInvasive = isInvasive
            self.ecologyType = ecologyType
            self.wikipediaUrl = wikipediaUrl
            self.wikipediaOverview = wikipediaOverview
            self.referenceImageUrl = referenceImageUrl
            self.additionalImagePaths = additionalImagePaths
            self.confidenceScore = confidenceScore
            self.isLocallyArchived = isLocallyArchived

            self.taxonomyKingdom = taxonomyKingdom
            self.taxonomyPhylum = taxonomyPhylum
            self.taxonomyClass = taxonomyClass
            self.taxonomyOrder = taxonomyOrder
            self.taxonomyFamily = taxonomyFamily
            self.taxonomyGenus = taxonomyGenus

            self.locationName = locationName
            self.weatherCondition = weatherCondition
            self.weatherTemperatureF = weatherTemperatureF

            self.collections = collections

            self.similarSpecies = similarSpecies
            self.lookalikesData = lookalikesData
            self.candidatesData = candidatesData
            self.iucnRedListStatus = iucnRedListStatus
            self.gpsLatitude = gpsLatitude
            self.gpsLongitude = gpsLongitude
            self.gpsElevation = gpsElevation
            self.zoomFactor = zoomFactor

            self.aiReasoning = aiReasoning
            self.habitatDescription = habitatDescription
            self.gbifTaxonKey = gbifTaxonKey

            self.estimatedSizeCm = estimatedSizeCm
            self.lifeStage = lifeStage
            self.reproductiveCondition = reproductiveCondition
            self.individualCount = individualCount
            self.ecologicalInteractions = ecologicalInteractions
            self.inferenceTier = inferenceTier
            self.customTags = customTags
            self.hasBeenViewed = hasBeenViewed
            self.userIdentificationOverride = userIdentificationOverride
            self.userConfirmedIdentification = userConfirmedIdentification
            self.isFlagged = isFlagged
            self.imageQualityScore = imageQualityScore
            self.alternativeCommonNames = alternativeCommonNames
            self.confirmedSpeciesId = confirmedSpeciesId
        }
    }
}
